### ISSUE TITLE
Support for audio groups

### ISSUE THREAD

**Issue by rgruebel** [nohum/chromecast-mqtt-connector#3]
At the moment audio groups are not supported because they have the same IP as one of the devices.
Do you think its possible to use the friendly_name instead? 
Also the player_state and some other propeties of the single devices are not correct if i stream something to a group (Maybe this is a limitation of pychromecast?).

**Comment by nohum** [comment]
I think using friendly name instead is possible, though the ip address in the MQTT topic is also used for connecting to the chromecast if it has not been discovered yet, meaning that would not work anymore (but you could still implement some sort of cache that would map previously known friendly name to IPs). 

Regarding the second issue. According to https://github.com/balloob/pychromecast/issues/65 pychromecast supports multi-room setups. My educated guess would be that this is because the same IP address is being used for multi-room and single-chromecast devices and there is no special handling build in by now (and I haven't tested this with multi-room setups actually). 

You could still check if you see log lines beginning with: 

```
DEBUG:pychromecast.controllers:Media:Received status
```

If these log lines show the correct properties when streaming to a group, then the problem lies definitely somewhere in the MQTT connector code.

**Comment by nohum** [comment]
Update: I talked to a friend who owns a multi-room setup and he controls it successfully via pychromecast.

**Comment by anderssv** [comment]
I would love for this to be supported as well. In addition I think friendly name as the queue name would be much better when integrating with other solutions. :)

Great work!

**Comment by nohum** [comment]
@anderssv Hey! I would love that too, but fortunately I currently do not have time to implement this. But if you are willing to implement that function and submit it as a PR I would gladly welcome that. 👍

**Comment by berryk** [comment]
Have proposed a pull request that publishes topics using friendly_name. This also allows groups to be supported.
